Repository ASE-Projekte-WS-2021/ase-ws-21-vp-manager, pull requests merged in 2022-04, with the labels that each got.

#224 Added studyStateClosed in Edit
  app/src/main/java/com/example/vpmanager/repositories/StudyEditRepository.java
Labels: bug

#225 Made Create Study Activity more responsive
  app/src/main/res/layout/fragment_create_study_final_step_two.xml
  app/src/main/res/layout/fragment_create_study_step_four_presence.xml
  app/src/main/res/layout/fragment_create_study_step_four_remote.xml
  app/src/main/res/layout/fragment_create_study_step_one.xml
  app/src/main/res/layout/fragment_create_study_step_three.xml
  app/src/main/res/layout/fragment_create_study_step_two.xml
Labels: create, improvement

#226 Update create study confirmation
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_finalStep.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_finalStep_two.java
  app/src/main/res/font/allerta_stencil.ttf
  app/src/main/res/layout/fragment_create_study_final_step.xml
  app/src/main/res/layout/fragment_create_study_final_step_three.xml
  app/src/main/res/layout/fragment_create_study_final_step_two.xml
  app/src/main/res/layout/fragment_create_study_step_one.xml
  app/src/main/res/values/strings.xml
Labels: design, create, improvement

#229 Added new categories
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepOne.java
  app/src/main/java/com/example/vpmanager/views/studyEditDetails/StudyEditDetailsFragment.java
  app/src/main/res/values/strings.xml
Labels: create, improvement

#231 Bugfix StudyState
  app/src/main/java/com/example/vpmanager/adapter/StudyDatesCreatorAdapter.java
  app/src/main/java/com/example/vpmanager/models/StudyDetailModel.java
  app/src/main/java/com/example/vpmanager/repositories/StudyRepository.java
  app/src/main/java/com/example/vpmanager/viewmodels/StudyEditViewModel.java
  app/src/main/java/com/example/vpmanager/views/studyCreatorDetails/StudyCreatorDetailsFragment.java
  config/checkstyle/checkstyle.xml
Labels: bug, pa

#234 Added Warning when changing study state
  app/src/main/java/com/example/vpmanager/views/studyCreatorDetails/StudyCreatorDetailsFragment.java
  app/src/main/res/values/strings.xml
Labels: pa, improvement

#238 App restructure personal information
  app/src/main/java/com/example/vpmanager/PA_ExpandableListDataPump.java
  app/src/main/java/com/example/vpmanager/adapter/CustomListViewAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/CustomListViewAdapterAppointments.java
  app/src/main/java/com/example/vpmanager/adapter/ViewPagerAdapter.java
  app/src/main/java/com/example/vpmanager/interfaces/GetAllDatesListener.java
  app/src/main/java/com/example/vpmanager/interfaces/GetAllStudiesListener.java
  app/src/main/java/com/example/vpmanager/interfaces/GetVpAndMatNrListener.java
  app/src/main/java/com/example/vpmanager/interfaces/StudyMetaDataListener.java
  app/src/main/java/com/example/vpmanager/repositories/HomeRepository.java
  app/src/main/java/com/example/vpmanager/repositories/OwnStudyRepository.java
  app/src/main/java/com/example/vpmanager/repositories/PersonalAccountRepository.java
  app/src/main/java/com/example/vpmanager/viewmodels/HomeViewModel.java
  app/src/main/java/com/example/vpmanager/viewmodels/OwnStudyViewModel.java
  app/src/main/java/com/example/vpmanager/viewmodels/PersonalAccountViewModel.java
  app/src/main/java/com/example/vpmanager/viewmodels/UpcomingAppointViewModel.java
  app/src/main/java/com/example/vpmanager/views/CustomAlertDialog.java
  app/src/main/java/com/example/vpmanager/views/CustomAlertReminder.java
  app/src/main/java/com/example/vpmanager/views/HomeFragment.java
  app/src/main/java/com/example/vpmanager/views/UpcomingAppointmentsFragment.java
  app/src/main/java/com/example/vpmanager/views/createStudy/CreateStudyFragment.java
  app/src/main/java/com/example/vpmanager/views/ownStudies/OwnStudyFragment.java
  app/src/main/java/com/example/vpmanager/views/ownStudies/PersonalAccountFragment.java
  app/src/main/java/com/example/vpmanager/views/ownStudies/SelfcreatedStudiesFragment.java
  app/src/main/java/com/example/vpmanager/views/studyDetails/StudyFragment.java
  app/src/main/java/com/example/vpmanager/views/studyEditDetails/StudyEditFragment.java
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_own_study.xml
  app/src/main/res/layout/fragment_personal_account.xml
  app/src/main/res/layout/fragment_selfcreated_study.xml
  app/src/main/res/layout/fragment_upcoming_appointments.xml
  app/src/main/res/navigation/nav_graph_main.xml
Labels: pa, improvement, architecture

#241 Bugfix Navigation switch between studyFragment und studyCreatorFragment
  app/src/main/java/com/example/vpmanager/PA_ExpandableListDataPump.java
  app/src/main/java/com/example/vpmanager/adapter/CustomListViewAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/CustomListViewAdapterAppointments.java
  app/src/main/java/com/example/vpmanager/views/FindStudyFragment.java
Labels: bug, pa

#243 Feature sort dates list
  app/src/main/java/com/example/vpmanager/adapter/EditSwipeableDatesAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/StudyDatesAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/StudyDatesCreatorAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/SwipeableDatesAdapter.java
  app/src/main/java/com/example/vpmanager/models/DateModel.java
  app/src/main/java/com/example/vpmanager/viewmodels/HomeViewModel.java
  app/src/main/java/com/example/vpmanager/viewmodels/StudyViewModel.java
Labels: find, date, improvement

#244 Removing expired dates
  app/src/main/java/com/example/vpmanager/models/DateModel.java
  app/src/main/java/com/example/vpmanager/viewmodels/StudyViewModel.java
Labels: find

#248 Feature Find Study Filter List
  app/src/main/java/com/example/vpmanager/adapter/StudyListAdapter.java
  app/src/main/java/com/example/vpmanager/views/FindStudyFragment.java
  app/src/main/res/drawable/ic_baseline_expand_less_24.xml
  app/src/main/res/drawable/ic_baseline_expand_more_24.xml
  app/src/main/res/drawable/ic_baseline_north_24.xml
  app/src/main/res/drawable/ic_baseline_south_24.xml
  app/src/main/res/layout/fragment_find_study.xml
Labels: find

#249 Cleanup create study
  app/src/main/java/com/example/vpmanager/Config.java
  app/src/main/java/com/example/vpmanager/repositories/CreateStudyRepository.java
  app/src/main/java/com/example/vpmanager/viewmodels/CreateStudyViewModel.java
  app/src/main/java/com/example/vpmanager/views/createStudy/CreateStudyFragment.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepFive.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepFour_Presence.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepFour_Remote.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepOne.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepThree.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepTwo.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_finalStep.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_finalStep_three.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_finalStep_two.java
  app/src/main/res/layout/fragment_create_study.xml
  app/src/main/res/layout/fragment_create_study_base.xml
  app/src/main/res/layout/fragment_create_study_final_step_three.xml
  app/src/main/res/layout/fragment_create_study_final_step_two.xml
  app/src/main/res/layout/fragment_create_study_step_five.xml
  app/src/main/res/layout/fragment_create_study_step_four_presence.xml
  app/src/main/res/layout/fragment_create_study_step_four_remote.xml
  app/src/main/res/layout/fragment_create_study_step_one.xml
  app/src/main/res/layout/fragment_create_study_step_three.xml
  app/src/main/res/layout/fragment_create_study_step_two.xml
  app/src/main/res/values/strings.xml
Labels: documentation, create, architecture

#255 Fixed bug with persitent dates
  app/src/main/java/com/example/vpmanager/views/createStudy/CreateStudyFragment.java
Labels: bug

#256 Dataloss warning
  app/src/main/java/com/example/vpmanager/views/mainActivity.java
  app/src/main/res/drawable/ic_baseline_warning_24.xml
Labels: pa, create

#257 Cleanup find study
  app/src/main/java/com/example/vpmanager/Config.java
  app/src/main/java/com/example/vpmanager/adapter/StudyListAdapter.java
  app/src/main/java/com/example/vpmanager/models/StudyMetaInfoModel.java
  app/src/main/java/com/example/vpmanager/repositories/StudyListRepository.java
  app/src/main/java/com/example/vpmanager/viewmodels/FindStudyViewModel.java
  app/src/main/java/com/example/vpmanager/views/FindStudyFragment.java
  app/src/main/java/com/example/vpmanager/views/createStudy/CreateStudyFragment.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_Base.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepFive.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepFour_Presence.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepFour_Remote.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepOne.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepThree.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepTwo.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_finalStep.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_finalStep_three.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_finalStep_two.java
  app/src/main/res/layout/fragment_find_study.xml
  app/src/main/res/layout/studylist_cart.xml
  app/src/main/res/values/strings.xml
Labels: documentation, architecture

#259 Removed double icons in find study
  app/src/main/java/com/example/vpmanager/adapter/StudyListAdapter.java
Labels: bug, find

#262 Restructured the login/register functionality into the mvvm pattern
  app/src/main/java/com/example/vpmanager/AccessDatabase.java
  app/src/main/java/com/example/vpmanager/interfaces/FirebaseAuthCreateListener.java
  app/src/main/java/com/example/vpmanager/interfaces/FirebaseAuthEmailListener.java
  app/src/main/java/com/example/vpmanager/interfaces/FirebaseAuthResetListener.java
  app/src/main/java/com/example/vpmanager/interfaces/LoginListener.java
  app/src/main/java/com/example/vpmanager/interfaces/RegisterListener.java
  app/src/main/java/com/example/vpmanager/repositories/LoginRegisterRepository.java
  app/src/main/java/com/example/vpmanager/viewmodels/LoginRegisterViewModel.java
  app/src/main/java/com/example/vpmanager/views/LoginFragment.java
  app/src/main/java/com/example/vpmanager/views/RegisterFragment.java
  app/src/main/java/com/example/vpmanager/views/createStudy/CreateStudyFragment.java
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_register.xml
  app/src/main/res/layout/pa_upcoming_listview_item.xml
  app/src/main/res/layout/studylist_cart.xml
  app/src/main/res/navigation/nav_graph_main.xml
Labels: login, improvement, architecture

#263 Filter Options for own Studies
  app/src/main/java/com/example/vpmanager/adapter/CustomListViewAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/CustomStudyListAdapter.java
  app/src/main/java/com/example/vpmanager/models/StudyObjectPa.java
  app/src/main/java/com/example/vpmanager/viewmodels/OwnStudyViewModel.java
  app/src/main/java/com/example/vpmanager/viewmodels/PersonalAccountViewModel.java
  app/src/main/java/com/example/vpmanager/views/ownStudies/PersonalAccountFragment.java
  app/src/main/java/com/example/vpmanager/views/ownStudies/SelfcreatedStudiesFragment.java
  app/src/main/res/layout/fragment_personal_account.xml
  app/src/main/res/layout/fragment_selfcreated_study.xml
  app/src/main/res/layout/pa_listview_item.xml
Labels: design, pa, improvement

#265 HomeLayout Responsive
  app/src/main/java/com/example/vpmanager/views/HomeFragment.java
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/pa_upcoming_listview_item.xml
  app/src/main/res/values/strings.xml
Labels: design

#270 Feature presets in study creations
  app/src/main/java/com/example/vpmanager/viewmodels/HomeViewModel.java
  app/src/main/java/com/example/vpmanager/views/HomeFragment.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepFour_Presence.java
  app/src/main/res/layout/fragment_create_study_step_four_presence.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: create

#271 Bugfix all appointments
  app/src/main/java/com/example/vpmanager/viewmodels/HomeViewModel.java
  app/src/main/java/com/example/vpmanager/viewmodels/UpcomingAppointViewModel.java
  app/src/main/java/com/example/vpmanager/views/HomeFragment.java
Labels: bug, pa

#272 Cleanup login/homescreen
  app/src/main/java/com/example/vpmanager/Config.java
  app/src/main/java/com/example/vpmanager/adapter/CustomListViewAdapterAppointments.java
  app/src/main/java/com/example/vpmanager/adapter/EditSwipeableDatesAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/SwipeableDatesAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/ViewPagerAdapter.java
  app/src/main/java/com/example/vpmanager/helper/EditSwipeToDeleteCallback.java
  app/src/main/java/com/example/vpmanager/helper/SwipeToDeleteCallback.java
  app/src/main/java/com/example/vpmanager/models/StudyObjectPa.java
  app/src/main/java/com/example/vpmanager/repositories/CreateStudyRepository.java
  app/src/main/java/com/example/vpmanager/repositories/HomeRepository.java
  app/src/main/java/com/example/vpmanager/repositories/LoginRegisterRepository.java
  app/src/main/java/com/example/vpmanager/viewmodels/HomeViewModel.java
  app/src/main/java/com/example/vpmanager/views/HomeFragment.java
  app/src/main/java/com/example/vpmanager/views/LoginFragment.java
  app/src/main/java/com/example/vpmanager/views/RegisterFragment.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepOne.java
  app/src/main/java/com/example/vpmanager/views/mainActivity.java
  app/src/main/res/layout/fragment_create_study_step_one.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/values/strings.xml
Labels: documentation, login, architecture

#274 Disable cancelAppointment Button if appointment already happend
  app/src/main/java/com/example/vpmanager/viewmodels/HomeViewModel.java
  app/src/main/java/com/example/vpmanager/viewmodels/StudyViewModel.java
  app/src/main/java/com/example/vpmanager/views/studyDetails/StudyDatesFragment.java
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: pa

#275 Redesigned the navigation drawer and menu items
  app/src/main/java/com/example/vpmanager/viewmodels/StudyViewModel.java
  app/src/main/java/com/example/vpmanager/views/mainActivity.java
  app/src/main/res/drawable/ic_outline_dashboard_24.xml
  app/src/main/res/layout/header_navigation_drawer.xml
  app/src/main/res/layout/pa_listview_item.xml
  app/src/main/res/layout/pa_upcoming_listview_item.xml
  app/src/main/res/menu/navigation_drawer.xml
  app/src/main/res/navigation/nav_graph_main.xml
  app/src/main/res/values/strings.xml
Labels: design, improvement

#276 Design home custom alert
  app/src/main/java/com/example/vpmanager/viewmodels/HomeViewModel.java
  app/src/main/java/com/example/vpmanager/views/CustomAlertDialog.java
  app/src/main/java/com/example/vpmanager/views/HomeFragment.java
  app/src/main/res/layout/custom_dialog.xml
Labels: design

#279 Disabled removing booked appointments
  app/src/main/java/com/example/vpmanager/adapter/EditSwipeableDatesAdapter.java
  app/src/main/res/values/strings.xml
Labels: pa, create

#285 platform for remote studies not displayed in detailView
  app/src/main/java/com/example/vpmanager/views/studyCreatorDetails/StudyCreatorDetailsFragment.java
  app/src/main/java/com/example/vpmanager/views/studyDetails/StudyDetailsFragment.java
Labels: bug

#288 display secondary platform
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/vpmanager/views/studyCreatorDetails/StudyCreatorDetailsFragment.java
  app/src/main/java/com/example/vpmanager/views/studyDetails/StudyDetailsFragment.java
Labels: bug, design

#289 removed unused textview from layout
  app/src/main/java/com/example/vpmanager/adapter/EditSwipeableDatesAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/StudyDatesAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/SwipeableDatesAdapter.java
  app/src/main/res/layout/date_item.xml
Labels: design, date

#292 Added a loading screen, changed some layouts and renamed strings
  app/src/main/java/com/example/vpmanager/viewmodels/PersonalAccountViewModel.java
  app/src/main/java/com/example/vpmanager/views/CustomAlertDialog.java
  app/src/main/java/com/example/vpmanager/views/HomeFragment.java
  app/src/main/java/com/example/vpmanager/views/createStudy/CreateStudyFragment_Base.java
  app/src/main/res/drawable/gradient.xml
  app/src/main/res/layout/fragment_create_study.xml
  app/src/main/res/layout/fragment_create_study_base.xml
  app/src/main/res/layout/fragment_create_study_step_four_presence.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: design, pa, improvement

#295 Bugfix snackbar
  app/src/main/java/com/example/vpmanager/views/studyCreatorDetails/StudyCreatorDatesFragment.java
  app/src/main/java/com/example/vpmanager/views/studyCreatorDetails/StudyCreatorDetailsFragment.java
  app/src/main/java/com/example/vpmanager/views/studyCreatorDetails/StudyCreatorFragment.java
  app/src/main/java/com/example/vpmanager/views/studyEditDetails/StudyEditDetailsFragment.java
  app/src/main/res/navigation/nav_graph_main.xml
Labels: improvement

#296 Improvement read me
  README.md
  wiki_Images/app_screenshots.png
Labels: documentation

#297 Bugfix navcontroller and save study button
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/vpmanager/adapter/StudyListAdapter.java
  app/src/main/res/layout/fragment_create_study.xml
  app/src/main/res/layout/fragment_create_study_base.xml
  app/src/main/res/layout/fragment_edit_study_details.xml
  app/src/main/res/layout/fragment_find_study.xml
Labels: design, improvement
