Repository ASE-Projekte-WS-2021/ase-ws-21-vp-manager, pull requests merged in 2022-03, with the labels that each got.

#77 Improvement study creation
  .idea/libraries/Gradle__androidx_asynclayoutinflater_asynclayoutinflater_1_0_0_aar.xml
  .idea/libraries/Gradle__androidx_legacy_legacy_support_core_ui_1_0_0_aar.xml
  .idea/libraries/Gradle__androidx_legacy_legacy_support_v4_1_0_0_aar.xml
  .idea/libraries/Gradle__androidx_media_media_1_0_0_aar.xml
  .idea/libraries/Gradle__androidx_slidingpanelayout_slidingpanelayout_1_0_0_aar.xml
  .idea/libraries/Gradle__androidx_swiperefreshlayout_swiperefreshlayout_1_0_0_aar.xml
  .idea/libraries/Gradle__com_kofigyan_stateprogressbar_stateprogressbar_1_0_0_aar.xml
  .idea/misc.xml
  .idea/modules/app/VP_Managaer.app.iml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/vpmanager/createStudyActivity.java
  app/src/main/java/com/example/vpmanager/createStudyFragment_Base.java
  app/src/main/java/com/example/vpmanager/createStudyFragment_StepFive.java
  app/src/main/java/com/example/vpmanager/createStudyFragment_StepFour_Presence.java
  app/src/main/java/com/example/vpmanager/createStudyFragment_StepFour_Remote.java
  app/src/main/java/com/example/vpmanager/createStudyFragment_StepOne.java
  app/src/main/java/com/example/vpmanager/createStudyFragment_StepOne_Contact.java
  app/src/main/java/com/example/vpmanager/createStudyFragment_StepThree.java
  app/src/main/java/com/example/vpmanager/createStudyFragment_StepTwo.java
  app/src/main/java/com/example/vpmanager/createStudyFragment_finalStep.java
  app/src/main/java/com/example/vpmanager/createStudyFragment_finalStep_three.java
  app/src/main/java/com/example/vpmanager/createStudyFragment_finalStep_two.java
  app/src/main/res/anim/enter_from_left.xml
  app/src/main/res/anim/enter_from_right.xml
  app/src/main/res/anim/exit_to_left.xml
  app/src/main/res/anim/exit_to_right.xml
  app/src/main/res/drawable/ic_baseline_add_24.xml
  app/src/main/res/layout/activity_create_study.xml
  app/src/main/res/layout/fragment_create_study_base.xml
  app/src/main/res/layout/fragment_create_study_final_step.xml
  app/src/main/res/layout/fragment_create_study_final_step_three.xml
  app/src/main/res/layout/fragment_create_study_final_step_two.xml
  app/src/main/res/layout/fragment_create_study_step_five.xml
  app/src/main/res/layout/fragment_create_study_step_four_presence.xml
  app/src/main/res/layout/fragment_create_study_step_four_remote.xml
  app/src/main/res/layout/fragment_create_study_step_one.xml
  app/src/main/res/layout/fragment_create_study_step_one_contact.xml
  app/src/main/res/layout/fragment_create_study_step_three.xml
  app/src/main/res/layout/fragment_create_study_step_two.xml
  app/src/main/res/values/strings.xml
Labels: create, improvement

#80 Added missing files
  app/src/main/java/com/example/vpmanager/findStudyActivity.java
  app/src/main/java/com/example/vpmanager/studyListAdapter.java
  app/src/main/res/anim/animation.xml
  app/src/main/res/drawable/gradient.xml
  app/src/main/res/layout/studylist_cart.xml
  app/src/main/res/layout/studylist_cart_ds.xml
  app/src/main/res/layout/studylist_cart_vr.xml
Labels: bug, design

#83 Fixed some bugs and changed design
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/vpmanager/adapter/StudyListAdapter.java
  app/src/main/java/com/example/vpmanager/models/StudyMetaInfoModel.java
  app/src/main/java/com/example/vpmanager/repositories/StudyListRepository.java
  app/src/main/java/com/example/vpmanager/studyListAdapter.java
  app/src/main/java/com/example/vpmanager/views/createStudyActivity.java
  app/src/main/java/com/example/vpmanager/views/createStudyFragment_Base.java
  app/src/main/java/com/example/vpmanager/views/createStudyFragment_StepFive.java
  app/src/main/java/com/example/vpmanager/views/createStudyFragment_StepFour_Presence.java
  app/src/main/java/com/example/vpmanager/views/createStudyFragment_StepFour_Remote.java
  app/src/main/java/com/example/vpmanager/views/createStudyFragment_StepOne.java
  app/src/main/java/com/example/vpmanager/views/createStudyFragment_StepOne_Contact.java
  app/src/main/java/com/example/vpmanager/views/createStudyFragment_StepThree.java
  app/src/main/java/com/example/vpmanager/views/createStudyFragment_StepTwo.java
  app/src/main/java/com/example/vpmanager/views/createStudyFragment_finalStep.java
  app/src/main/java/com/example/vpmanager/views/createStudyFragment_finalStep_three.java
  app/src/main/java/com/example/vpmanager/views/createStudyFragment_finalStep_two.java
  app/src/main/res/layout/activity_create_study.xml
  app/src/main/res/layout/fragment_create_study_base.xml
  app/src/main/res/layout/fragment_create_study_final_step.xml
  app/src/main/res/layout/fragment_create_study_final_step_three.xml
  app/src/main/res/layout/fragment_create_study_final_step_two.xml
  app/src/main/res/layout/fragment_create_study_step_five.xml
  app/src/main/res/layout/fragment_create_study_step_four_presence.xml
  app/src/main/res/layout/fragment_create_study_step_four_remote.xml
  app/src/main/res/layout/fragment_create_study_step_one.xml
  app/src/main/res/layout/fragment_create_study_step_one_contact.xml
  app/src/main/res/layout/fragment_create_study_step_three.xml
  app/src/main/res/layout/fragment_create_study_step_two.xml
  app/src/main/res/layout/fragment_study.xml
  app/src/main/res/layout/header_navigation_drawer.xml
  app/src/main/res/layout/studylist_cart.xml
  app/src/main/res/layout/studylist_cart_ar.xml
  app/src/main/res/layout/studylist_cart_ds.xml
  app/src/main/res/layout/studylist_cart_vr.xml
Labels: design

#85 Cache in study creation
  app/src/main/java/com/example/vpmanager/views/createStudyActivity.java
  app/src/main/java/com/example/vpmanager/views/createStudyFragment_StepFive.java
  app/src/main/java/com/example/vpmanager/views/createStudyFragment_StepFour_Presence.java
  app/src/main/java/com/example/vpmanager/views/createStudyFragment_StepFour_Remote.java
  app/src/main/java/com/example/vpmanager/views/createStudyFragment_StepOne.java
  app/src/main/java/com/example/vpmanager/views/createStudyFragment_StepOne_Contact.java
  app/src/main/java/com/example/vpmanager/views/createStudyFragment_StepThree.java
  app/src/main/java/com/example/vpmanager/views/createStudyFragment_StepTwo.java
  app/src/main/java/com/example/vpmanager/views/createStudyFragment_finalStep_three.java
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: create

#87 Redesigned the screen where the studies created by the user can be seen
  app/src/main/java/com/example/vpmanager/views/ownStudyFragment.java
  app/src/main/res/layout/fragment_own_study.xml
  app/src/main/res/navigation/nav_graph_main.xml
Labels: design, improvement

#91 Navigation Update Studycreation
  app/src/main/java/com/example/vpmanager/createStudy/createStudyActivity.java
  app/src/main/res/drawable/ic_baseline_arrow_back_24.xml
  app/src/main/res/layout/activity_create_study.xml
Labels: create

#93 Bugfix Overlap
  app/src/main/res/layout/fragment_find_study.xml
  app/src/main/res/layout/fragment_study.xml
Labels: bug

#95 Navigation drawer header overlap and double load in findStudyFragment…
  app/src/main/java/com/example/vpmanager/views/findStudyFragment.java
  app/src/main/res/layout/header_navigation_drawer.xml
Labels: bug

#96 Bug fix
  .idea/navEditor.xml
  app/src/main/java/com/example/vpmanager/PA_ExpandableListDataPump.java
  app/src/main/java/com/example/vpmanager/views/editStudyFragment.java
  app/src/main/java/com/example/vpmanager/views/ownStudyFragment.java
  app/src/main/res/layout/fragment_creator_study.xml
  app/src/main/res/layout/fragment_edit_study.xml
  app/src/main/res/layout/fragment_study.xml
  app/src/main/res/navigation/nav_graph_main.xml
Labels: bug, improvement

#97 fixed layout issues
  app/src/main/res/layout/fragment_create_study_final_step.xml
  app/src/main/res/layout/fragment_create_study_final_step_two.xml
Labels: bug, design

#98 Changed a previous bugfix
  app/src/main/java/com/example/vpmanager/views/studyFragment.java
  app/src/main/res/layout/fragment_find_study.xml
  app/src/main/res/layout/fragment_study.xml
  app/src/main/res/navigation/nav_graph_main.xml
Labels: design

#101 Login Feature
  .idea/libraries/Gradle__com_google_firebase_firebase_common_20_0_0_aar.xml
  .idea/navEditor.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/vpmanager/views/homeFragment.java
  app/src/main/java/com/example/vpmanager/views/loginFragment.java
  app/src/main/java/com/example/vpmanager/views/mainActivity.java
  app/src/main/res/drawable/ic_baseline_exit_to_app_24.xml
  app/src/main/res/drawable/ic_baseline_lock_24.xml
  app/src/main/res/drawable/ic_baseline_person_24.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/menu/navigation_drawer.xml
  app/src/main/res/navigation/nav_graph_main.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: login

#103 Addition of Verficiation Email
  app/src/main/java/com/example/vpmanager/views/homeFragment.java
  app/src/main/java/com/example/vpmanager/views/loginFragment.java
  app/src/main/java/com/example/vpmanager/views/mainActivity.java
Labels: login

#105 Fixed Bug
  app/src/main/java/com/example/vpmanager/views/homeFragment.java
  app/src/main/java/com/example/vpmanager/views/loginFragment.java
  app/src/main/java/com/example/vpmanager/views/mainActivity.java
  app/src/main/res/layout/fragment_login.xml
Labels: bug

#107 Feature reset password
  app/src/main/java/com/example/vpmanager/views/loginFragment.java
Labels: login

#109 Feature limit navigation
  app/src/main/java/com/example/vpmanager/DrawerController.java
  app/src/main/java/com/example/vpmanager/views/homeFragment.java
  app/src/main/java/com/example/vpmanager/views/loginFragment.java
  app/src/main/java/com/example/vpmanager/views/mainActivity.java
Labels: login

#117 Study View Rework
  app/src/main/java/com/example/vpmanager/views/studyDates.java
  app/src/main/java/com/example/vpmanager/views/studyDetails.java
  app/src/main/java/com/example/vpmanager/views/studyFragment.java
  app/src/main/res/drawable/ic_baseline_edit_calendar_24.xml
  app/src/main/res/font/.xml
  app/src/main/res/font/bentham.xml
  app/src/main/res/font/maven_pro.xml
  app/src/main/res/layout/fragment_study.xml
  app/src/main/res/layout/fragment_study_dates.xml
  app/src/main/res/layout/fragment_study_details.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/preloaded_fonts.xml
  app/src/main/res/values/strings.xml
Labels: help, design, improvement

#118 create study wizard improvement
  app/src/main/res/layout/fragment_create_study_final_step_three.xml
  app/src/main/res/layout/fragment_create_study_step_four_presence.xml
  app/src/main/res/values/strings.xml
Labels: create, improvement

#121 Added Weekdays to the date
  app/src/main/java/com/example/vpmanager/createStudy/createStudyActivity.java
  app/src/main/java/com/example/vpmanager/createStudy/createStudyFragment_StepFive.java
Labels: date

#119 App restructure mvvm
  app/.gitignore
  app/src/main/java/com/example/vpmanager/AccessDatabase.java
  app/src/main/java/com/example/vpmanager/adapter/StudyListAdapter.java
  app/src/main/java/com/example/vpmanager/createStudy/createStudyActivity.java
  app/src/main/java/com/example/vpmanager/repositories/StudyListRepository.java
  app/src/main/java/com/example/vpmanager/viewmodels/FindStudyViewModel.java
  app/src/main/java/com/example/vpmanager/views/FindStudyFragment.java
  app/src/main/java/com/example/vpmanager/views/findStudyFragment.java
  app/src/main/java/com/example/vpmanager/views/homeFragment.java
  app/src/main/java/com/example/vpmanager/views/loginFragment.java
  app/src/main/java/com/example/vpmanager/views/mainActivity.java
  app/src/main/java/com/example/vpmanager/views/studyCreatorFragment.java
  app/src/main/res/layout/activity_create_study.xml
  app/src/main/res/layout/fragment_creator_study.xml
  app/src/main/res/menu/navigation_drawer.xml
  app/src/main/res/navigation/nav_graph_main.xml
Labels: find, improvement, architecture

#126 Updating study cart design
  app/src/main/java/com/example/vpmanager/adapter/StudyListAdapter.java
  app/src/main/res/drawable/gradient.xml
  app/src/main/res/drawable/ic_baseline_category_24.xml
  app/src/main/res/drawable/ic_baseline_category_24_white.xml
  app/src/main/res/layout/studylist_cart.xml
Labels: design, find, improvement

#132 Rework pa home
  app/src/main/java/com/example/vpmanager/PA_ExpandableListDataPump.java
  app/src/main/java/com/example/vpmanager/views/CustomAlertDialog.java
  app/src/main/java/com/example/vpmanager/views/CustomAlertReminder.java
  app/src/main/java/com/example/vpmanager/views/UpcomingAppointments.java
  app/src/main/java/com/example/vpmanager/views/homeFragment.java
  app/src/main/java/com/example/vpmanager/views/mainActivity.java
  app/src/main/java/com/example/vpmanager/views/personalAccountFragment.java
  app/src/main/res/drawable/ic_settings_preferences.xml
  app/src/main/res/layout/custom_dialog.xml
  app/src/main/res/layout/custom_reminder.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_dates.xml
  app/src/main/res/layout/fragment_personal_account.xml
Labels: db, pa, improvement

#135 App restructure mvvm study details
  app/src/main/java/com/example/vpmanager/AccessDatabase.java
  app/src/main/java/com/example/vpmanager/adapter/StudyDatesAdapter.java
  app/src/main/java/com/example/vpmanager/interfaces/SelectUnselectDateListener.java
  app/src/main/java/com/example/vpmanager/interfaces/StudyDatesListener.java
  app/src/main/java/com/example/vpmanager/interfaces/StudyDetailsListener.java
  app/src/main/java/com/example/vpmanager/models/DateModel.java
  app/src/main/java/com/example/vpmanager/models/StudyDetailModel.java
  app/src/main/java/com/example/vpmanager/repositories/StudyRepository.java
  app/src/main/java/com/example/vpmanager/viewmodels/StudyViewModel.java
  app/src/main/java/com/example/vpmanager/views/StudyFragment.java
  app/src/main/java/com/example/vpmanager/views/studyDates.java
  app/src/main/java/com/example/vpmanager/views/studyDetails.java
  app/src/main/java/com/example/vpmanager/views/studyDetails/StudyDatesFragment.java
  app/src/main/java/com/example/vpmanager/views/studyDetails/StudyDetailsFragment.java
  app/src/main/java/com/example/vpmanager/views/studyDetails/StudyFragment.java
  app/src/main/res/layout/date_item.xml
  app/src/main/res/layout/fragment_creator_study.xml
  app/src/main/res/layout/fragment_study.xml
  app/src/main/res/layout/fragment_study_dates.xml
  app/src/main/res/layout/fragment_study_details.xml
  app/src/main/res/navigation/nav_graph_main.xml
  app/src/main/res/values/strings.xml
Labels: improvement, architecture

#138 personalAccount as starting Point
  app/src/main/java/com/example/vpmanager/adapter/CustomListViewAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/CustomListViewAdapterAppointments.java
  app/src/main/java/com/example/vpmanager/views/UpcomingAppointments.java
  app/src/main/java/com/example/vpmanager/views/homeFragment.java
  app/src/main/java/com/example/vpmanager/views/mainActivity.java
  app/src/main/java/com/example/vpmanager/views/personalAccountFragment.java
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_dates.xml
  app/src/main/res/layout/fragment_personal_account.xml
  app/src/main/res/layout/pa_listview_item.xml
  app/src/main/res/layout/pa_upcoming_listview_item.xml
  app/src/main/res/menu/navigation_drawer.xml
  app/src/main/res/navigation/nav_graph_main.xml
Labels: pa, improvement

#140 Improvement create study dates and colors
  app/src/main/java/com/example/vpmanager/createStudy/createStudyActivity.java
  app/src/main/java/com/example/vpmanager/createStudy/createStudyFragment_StepFive.java
  app/src/main/res/drawable/border.xml
  app/src/main/res/layout/activity_create_study.xml
  app/src/main/res/layout/fragment_create_study_final_step.xml
  app/src/main/res/layout/fragment_create_study_final_step_three.xml
  app/src/main/res/layout/fragment_create_study_final_step_two.xml
  app/src/main/res/layout/fragment_create_study_step_five.xml
  app/src/main/res/layout/fragment_create_study_step_one.xml
  app/src/main/res/layout/fragment_create_study_step_three.xml
  app/src/main/res/values/strings.xml
Labels: design, create, date

#141 Adjustment of Progressbar
  app/src/main/java/com/example/vpmanager/createStudy/createStudyActivity.java
Labels: create, improvement

#142 User identification via Email
  app/src/main/java/com/example/vpmanager/createStudy/createStudyActivity.java
  app/src/main/java/com/example/vpmanager/createStudy/createStudyFragment_StepTwo.java
  app/src/main/java/com/example/vpmanager/views/mainActivity.java
  app/src/main/res/layout/fragment_create_study_step_five.xml
  app/src/main/res/layout/fragment_create_study_step_four_presence.xml
  app/src/main/res/layout/fragment_create_study_step_four_remote.xml
  app/src/main/res/layout/fragment_create_study_step_one.xml
  app/src/main/res/layout/fragment_create_study_step_three.xml
  app/src/main/res/layout/fragment_create_study_step_two.xml
Labels: db, create

#143 Bugfix study selection
  app/src/main/java/com/example/vpmanager/interfaces/SelectDateListener.java
  app/src/main/java/com/example/vpmanager/interfaces/SelectUnselectDateListener.java
  app/src/main/java/com/example/vpmanager/interfaces/UnselectDateListener.java
  app/src/main/java/com/example/vpmanager/repositories/StudyRepository.java
  app/src/main/java/com/example/vpmanager/viewmodels/StudyViewModel.java
  app/src/main/java/com/example/vpmanager/views/studyDetails/StudyDatesFragment.java
Labels: improvement

#146 Release v5
  app/src/main/java/com/example/vpmanager/createStudy/createStudyActivity.java
  app/src/main/java/com/example/vpmanager/createStudy/createStudyFragment_StepFive.java
  app/src/main/java/com/example/vpmanager/createStudy/createStudyFragment_StepTwo.java
  app/src/main/java/com/example/vpmanager/interfaces/SelectDateListener.java
  app/src/main/java/com/example/vpmanager/interfaces/SelectUnselectDateListener.java
  app/src/main/java/com/example/vpmanager/interfaces/UnselectDateListener.java
  app/src/main/java/com/example/vpmanager/repositories/StudyRepository.java
  app/src/main/java/com/example/vpmanager/viewmodels/StudyViewModel.java
  app/src/main/java/com/example/vpmanager/views/mainActivity.java
  app/src/main/java/com/example/vpmanager/views/studyDetails/StudyDatesFragment.java
  app/src/main/res/drawable/border.xml
  app/src/main/res/layout/activity_create_study.xml
  app/src/main/res/layout/fragment_create_study_final_step.xml
  app/src/main/res/layout/fragment_create_study_final_step_three.xml
  app/src/main/res/layout/fragment_create_study_final_step_two.xml
  app/src/main/res/layout/fragment_create_study_step_five.xml
  app/src/main/res/layout/fragment_create_study_step_four_presence.xml
  app/src/main/res/layout/fragment_create_study_step_four_remote.xml
  app/src/main/res/layout/fragment_create_study_step_one.xml
  app/src/main/res/layout/fragment_create_study_step_three.xml
  app/src/main/res/layout/fragment_create_study_step_two.xml
  app/src/main/res/values/strings.xml
Labels: find, create, improvement

#147 sorting Lists
  app/src/main/java/com/example/vpmanager/PA_ExpandableListDataPump.java
  app/src/main/java/com/example/vpmanager/adapter/CustomListViewAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/CustomListViewAdapterAppointments.java
  app/src/main/java/com/example/vpmanager/views/StudyObject.java
  app/src/main/java/com/example/vpmanager/views/UpcomingAppointments.java
  app/src/main/java/com/example/vpmanager/views/mainActivity.java
  app/src/main/java/com/example/vpmanager/views/personalAccountFragment.java
  app/src/main/res/drawable/ic_baseline_date_range_24.xml
  app/src/main/res/drawable/ic_baseline_sort_by_alpha_24.xml
  app/src/main/res/layout/fragment_personal_account.xml
  app/src/main/res/layout/pa_listview_item.xml
  app/src/main/res/layout/pa_upcoming_listview_item.xml
Labels: pa, improvement

#150 Design - find studies
  app/src/main/res/layout/fragment_find_study.xml
  app/src/main/res/layout/studylist_cart.xml
  app/src/main/res/values/colors.xml
Labels: bug, design, improvement

#154 Bug fix navigation drawer
  app/src/main/java/com/example/vpmanager/PA_ExpandableListDataPump.java
  app/src/main/java/com/example/vpmanager/views/UpcomingAppointments.java
  app/src/main/java/com/example/vpmanager/views/homeFragment.java
  app/src/main/java/com/example/vpmanager/views/loginFragment.java
  app/src/main/java/com/example/vpmanager/views/mainActivity.java
  app/src/main/java/com/example/vpmanager/views/personalAccountFragment.java
  app/src/main/res/layout/date_item.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_personal_account.xml
Labels: bug, design, pa

#156 Made Study details scrollable
  app/src/main/res/layout/fragment_study_details.xml
Labels: bug

#161 Improvement study details responsive
  app/src/main/java/com/example/vpmanager/views/studyCreatorDetails/studyCreatorFragment.java
  app/src/main/res/drawable/ic_baseline_edit_note_24.xml
  app/src/main/res/drawable/ic_baseline_edit_note_24_red.xml
  app/src/main/res/layout/fragment_study_creator_details.xml
  app/src/main/res/layout/fragment_study_dates.xml
  app/src/main/res/layout/fragment_study_details.xml
  app/src/main/res/layout/study_details_new.xml
  app/src/main/res/values/strings.xml
Labels: design, improvement

#162 Release v8
  app/src/main/java/com/example/vpmanager/views/studyCreatorDetails/studyCreatorFragment.java
  app/src/main/res/drawable/ic_baseline_edit_note_24.xml
  app/src/main/res/drawable/ic_baseline_edit_note_24_red.xml
  app/src/main/res/layout/fragment_study_creator_details.xml
  app/src/main/res/layout/fragment_study_dates.xml
  app/src/main/res/layout/fragment_study_details.xml
  app/src/main/res/layout/study_details_new.xml
  app/src/main/res/values/strings.xml
Labels: design, improvement

#163 Made Layout more responsive (study View)
  app/src/main/res/layout/fragment_study_creator_details.xml
  app/src/main/res/layout/fragment_study_details.xml
Labels: design, improvement

#170 Fix Scrollbar on Register/Login Screen
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_register.xml
Labels: bug, login

#174 Bugfix
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: bug, architecture

#172 App restructure mvvm create study
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/vpmanager/AccessDatabase.java
  app/src/main/java/com/example/vpmanager/DrawerController.java
  app/src/main/java/com/example/vpmanager/adapter/CustomListViewAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/CustomListViewAdapterAppointments.java
  app/src/main/java/com/example/vpmanager/adapter/SwipeableDatesAdapter.java
  app/src/main/java/com/example/vpmanager/createStudy/createStudyFragment_StepTwo.java
  app/src/main/java/com/example/vpmanager/createStudy/createStudyFragment_finalStep.java
  app/src/main/java/com/example/vpmanager/createStudy/createStudyFragment_finalStep_two.java
  app/src/main/java/com/example/vpmanager/interfaces/CreateStudyListener.java
  app/src/main/java/com/example/vpmanager/models/StudyDetailModel.java
  app/src/main/java/com/example/vpmanager/models/StudyObjectPa.java
  app/src/main/java/com/example/vpmanager/repositories/CreateStudyRepository.java
  app/src/main/java/com/example/vpmanager/repositories/StudyRepository.java
  app/src/main/java/com/example/vpmanager/viewmodels/CreateStudyViewModel.java
  app/src/main/java/com/example/vpmanager/views/createStudy/CreateStudyFragment.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyActivity.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_Base.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepFive.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepFour_Presence.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepFour_Remote.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepOne.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepThree.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepTwo.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_finalStep.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_finalStep_three.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_finalStep_two.java
  app/src/main/java/com/example/vpmanager/views/homeFragment.java
  app/src/main/java/com/example/vpmanager/views/mainActivity.java
  app/src/main/java/com/example/vpmanager/views/personalAccountFragment.java
  app/src/main/res/layout/activity_create_study.xml
  app/src/main/res/layout/fragment_create_study.xml
  app/src/main/res/layout/fragment_create_study_base.xml
  app/src/main/res/layout/fragment_create_study_final_step.xml
  app/src/main/res/layout/fragment_create_study_final_step_three.xml
  app/src/main/res/layout/fragment_create_study_final_step_two.xml
  app/src/main/res/layout/fragment_create_study_step_five.xml
  app/src/main/res/layout/fragment_create_study_step_four_presence.xml
  app/src/main/res/layout/fragment_create_study_step_four_remote.xml
  app/src/main/res/layout/fragment_create_study_step_one.xml
  app/src/main/res/layout/fragment_create_study_step_three.xml
  app/src/main/res/layout/fragment_create_study_step_two.xml
  app/src/main/res/layout/fragment_find_study.xml
  app/src/main/res/menu/navigation_drawer.xml
  app/src/main/res/navigation/nav_graph_main.xml
  config/checkstyle/checkstyle.xml
Labels: create, improvement, architecture

#175 Release v0.1.0
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/vpmanager/AccessDatabase.java
  app/src/main/java/com/example/vpmanager/DrawerController.java
  app/src/main/java/com/example/vpmanager/adapter/CustomListViewAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/CustomListViewAdapterAppointments.java
  app/src/main/java/com/example/vpmanager/adapter/SwipeableDatesAdapter.java
  app/src/main/java/com/example/vpmanager/createStudy/createStudyFragment_StepTwo.java
  app/src/main/java/com/example/vpmanager/createStudy/createStudyFragment_finalStep.java
  app/src/main/java/com/example/vpmanager/createStudy/createStudyFragment_finalStep_two.java
  app/src/main/java/com/example/vpmanager/interfaces/CreateStudyListener.java
  app/src/main/java/com/example/vpmanager/models/StudyDetailModel.java
  app/src/main/java/com/example/vpmanager/models/StudyObjectPa.java
  app/src/main/java/com/example/vpmanager/repositories/CreateStudyRepository.java
  app/src/main/java/com/example/vpmanager/repositories/StudyRepository.java
  app/src/main/java/com/example/vpmanager/viewmodels/CreateStudyViewModel.java
  app/src/main/java/com/example/vpmanager/views/createStudy/CreateStudyFragment.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyActivity.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_Base.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepFive.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepFour_Presence.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepFour_Remote.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepOne.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepThree.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepTwo.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_finalStep.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_finalStep_three.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_finalStep_two.java
  app/src/main/java/com/example/vpmanager/views/homeFragment.java
  app/src/main/java/com/example/vpmanager/views/mainActivity.java
  app/src/main/java/com/example/vpmanager/views/personalAccountFragment.java
  app/src/main/res/layout/activity_create_study.xml
  app/src/main/res/layout/fragment_create_study.xml
  app/src/main/res/layout/fragment_create_study_base.xml
  app/src/main/res/layout/fragment_create_study_final_step.xml
  app/src/main/res/layout/fragment_create_study_final_step_three.xml
  app/src/main/res/layout/fragment_create_study_final_step_two.xml
  app/src/main/res/layout/fragment_create_study_step_five.xml
  app/src/main/res/layout/fragment_create_study_step_four_presence.xml
  app/src/main/res/layout/fragment_create_study_step_four_remote.xml
  app/src/main/res/layout/fragment_create_study_step_one.xml
  app/src/main/res/layout/fragment_create_study_step_three.xml
  app/src/main/res/layout/fragment_create_study_step_two.xml
  app/src/main/res/layout/fragment_find_study.xml
  app/src/main/res/menu/navigation_drawer.xml
  app/src/main/res/navigation/nav_graph_main.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
  config/checkstyle/checkstyle.xml
Labels: design, create, improvement, architecture

#178 Rework home fragment
  .idea/modules.xml
  app/build.gradle
  app/src/main/java/com/example/vpmanager/PA_ExpandableListDataPump.java
  app/src/main/java/com/example/vpmanager/adapter/CustomListViewAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/CustomListViewAdapterAppointments.java
  app/src/main/java/com/example/vpmanager/models/StudyObjectPa.java
  app/src/main/java/com/example/vpmanager/views/CustomAlertDialog.java
  app/src/main/java/com/example/vpmanager/views/CustomAlertReminder.java
  app/src/main/java/com/example/vpmanager/views/SelfcreatedStudiesFragment.java
  app/src/main/java/com/example/vpmanager/views/StudyObject.java
  app/src/main/java/com/example/vpmanager/views/UpcomingAppointmentsFragment.java
  app/src/main/java/com/example/vpmanager/views/homeFragment.java
  app/src/main/java/com/example/vpmanager/views/ownStudyFragment.java
  app/src/main/java/com/example/vpmanager/views/personalAccountFragment.java
  app/src/main/res/drawable/home_gradient.xml
  app/src/main/res/drawable/ic_baseline_star_24.xml
  app/src/main/res/layout/custom_reminder.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_own_study.xml
  app/src/main/res/layout/fragment_personal_account.xml
  app/src/main/res/layout/fragment_selfcreated_study.xml
  app/src/main/res/layout/fragment_upcoming_appointments.xml
  app/src/main/res/layout/pa_listview_item.xml
  app/src/main/res/layout/pa_upcoming_listview_item.xml
  app/src/main/res/navigation/nav_graph_main.xml
Labels: pa, improvement

#179 Release v0.1.1
  .idea/modules.xml
  app/build.gradle
  app/src/main/java/com/example/vpmanager/PA_ExpandableListDataPump.java
  app/src/main/java/com/example/vpmanager/adapter/CustomListViewAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/CustomListViewAdapterAppointments.java
  app/src/main/java/com/example/vpmanager/models/StudyObjectPa.java
  app/src/main/java/com/example/vpmanager/views/CustomAlertDialog.java
  app/src/main/java/com/example/vpmanager/views/CustomAlertReminder.java
  app/src/main/java/com/example/vpmanager/views/SelfcreatedStudiesFragment.java
  app/src/main/java/com/example/vpmanager/views/StudyObject.java
  app/src/main/java/com/example/vpmanager/views/UpcomingAppointmentsFragment.java
  app/src/main/java/com/example/vpmanager/views/homeFragment.java
  app/src/main/java/com/example/vpmanager/views/ownStudyFragment.java
  app/src/main/java/com/example/vpmanager/views/personalAccountFragment.java
  app/src/main/res/drawable/home_gradient.xml
  app/src/main/res/drawable/ic_baseline_star_24.xml
  app/src/main/res/layout/custom_reminder.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_own_study.xml
  app/src/main/res/layout/fragment_personal_account.xml
  app/src/main/res/layout/fragment_selfcreated_study.xml
  app/src/main/res/layout/fragment_upcoming_appointments.xml
  app/src/main/res/layout/pa_listview_item.xml
  app/src/main/res/layout/pa_upcoming_listview_item.xml
  app/src/main/res/navigation/nav_graph_main.xml
Labels: design, pa, improvement

#183 The list of dates in the create study process is now swipeable
  app/src/main/java/com/example/vpmanager/adapter/SwipeableDatesAdapter.java
  app/src/main/java/com/example/vpmanager/helper/SwipeToDeleteCallback.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepFive.java
  app/src/main/res/drawable/ic_baseline_delete_24.xml
  app/src/main/res/layout/fragment_create_study_step_five.xml
Labels: create, improvement

#191 Feature study state UI
  app/src/main/java/com/example/vpmanager/adapter/StudyDatesCreatorAdapter.java
  app/src/main/java/com/example/vpmanager/views/homeFragment.java
  app/src/main/java/com/example/vpmanager/views/studyCreatorDetails/StudyCreatorDatesFragment.java
  app/src/main/java/com/example/vpmanager/views/studyCreatorDetails/StudyCreatorDetailsFragment.java
  app/src/main/res/drawable/ic_baseline_check_24.xml
  app/src/main/res/drawable/ic_baseline_close_24.xml
  app/src/main/res/layout/date_creator_item.xml
  app/src/main/res/layout/fragment_creator_study_dates.xml
  app/src/main/res/layout/fragment_study_creator_details.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: design, pa

#192 Improvement create study
  app/src/main/java/com/example/vpmanager/views/createStudy/CreateStudyFragment.java
  app/src/main/res/layout/fragment_create_study.xml
  app/src/main/res/navigation/nav_graph_create.xml
Labels: create, improvement, architecture

#197 Feature Date State
  app/src/main/java/com/example/vpmanager/PA_ExpandableListDataPump.java
  app/src/main/java/com/example/vpmanager/adapter/CustomListViewAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/StudyDatesCreatorAdapter.java
  app/src/main/java/com/example/vpmanager/models/DateModel.java
  app/src/main/java/com/example/vpmanager/repositories/StudyRepository.java
  app/src/main/java/com/example/vpmanager/viewmodels/CreateStudyViewModel.java
  app/src/main/java/com/example/vpmanager/views/personalAccountFragment.java
  app/src/main/res/layout/date_creator_item.xml
  app/src/main/res/navigation/nav_graph_main.xml
Labels: design, pa

#198 Feature Study State
  app/src/main/java/com/example/vpmanager/PA_ExpandableListDataPump.java
  app/src/main/java/com/example/vpmanager/repositories/StudyListRepository.java
  app/src/main/java/com/example/vpmanager/viewmodels/CreateStudyViewModel.java
  app/src/main/java/com/example/vpmanager/views/studyCreatorDetails/StudyCreatorDetailsFragment.java
  app/src/main/res/drawable/ic_baseline_refresh_24.xml
Labels: design, pa

#199 Release v0.1.2
  app/src/main/java/com/example/vpmanager/PA_ExpandableListDataPump.java
  app/src/main/java/com/example/vpmanager/adapter/CustomListViewAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/StudyDatesCreatorAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/SwipeableDatesAdapter.java
  app/src/main/java/com/example/vpmanager/helper/SwipeToDeleteCallback.java
  app/src/main/java/com/example/vpmanager/models/DateModel.java
  app/src/main/java/com/example/vpmanager/repositories/StudyListRepository.java
  app/src/main/java/com/example/vpmanager/repositories/StudyRepository.java
  app/src/main/java/com/example/vpmanager/viewmodels/CreateStudyViewModel.java
  app/src/main/java/com/example/vpmanager/views/createStudy/CreateStudyFragment.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepFive.java
  app/src/main/java/com/example/vpmanager/views/homeFragment.java
  app/src/main/java/com/example/vpmanager/views/personalAccountFragment.java
  app/src/main/java/com/example/vpmanager/views/studyCreatorDetails/StudyCreatorDatesFragment.java
  app/src/main/java/com/example/vpmanager/views/studyCreatorDetails/StudyCreatorDetailsFragment.java
  app/src/main/res/drawable/ic_baseline_check_24.xml
  app/src/main/res/drawable/ic_baseline_close_24.xml
  app/src/main/res/drawable/ic_baseline_delete_24.xml
  app/src/main/res/drawable/ic_baseline_refresh_24.xml
  app/src/main/res/layout/date_creator_item.xml
  app/src/main/res/layout/fragment_create_study.xml
  app/src/main/res/layout/fragment_create_study_step_five.xml
  app/src/main/res/layout/fragment_creator_study_dates.xml
  app/src/main/res/layout/fragment_study_creator_details.xml
  app/src/main/res/navigation/nav_graph_create.xml
  app/src/main/res/navigation/nav_graph_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: design, pa

#201 Remove Whitespaces at login and register
  app/src/main/java/com/example/vpmanager/views/loginFragment.java
  app/src/main/java/com/example/vpmanager/views/registerFragment.java
Labels: login

#203 Bugfix create study
  app/build.gradle
  app/src/main/java/com/example/vpmanager/views/FindStudyFragment.java
  app/src/main/java/com/example/vpmanager/views/createStudy/CreateStudyFragment.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyActivity.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepOne.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepTwo.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_finalStep.java
  app/src/main/res/drawable/border.xml
  app/src/main/res/layout/activity_create_study.xml
  app/src/main/res/layout/fragment_create_study_base.xml
  app/src/main/res/layout/fragment_create_study_final_step.xml
  app/src/main/res/layout/fragment_create_study_final_step_three.xml
  app/src/main/res/layout/fragment_create_study_final_step_two.xml
  app/src/main/res/layout/fragment_create_study_step_five.xml
  app/src/main/res/layout/fragment_create_study_step_four_presence.xml
  app/src/main/res/layout/fragment_create_study_step_four_remote.xml
  app/src/main/res/layout/fragment_create_study_step_one.xml
  app/src/main/res/layout/fragment_create_study_step_three.xml
  app/src/main/res/layout/fragment_create_study_step_two.xml
  app/src/main/res/layout/material_dropdown_item.xml
  app/src/main/res/navigation/nav_graph_create.xml
  app/src/main/res/navigation/nav_graph_main.xml
  app/src/main/res/values/strings.xml
Labels: design, create, improvement

#204 Added redirection to login
  app/src/main/java/com/example/vpmanager/views/homeFragment.java
  app/src/main/java/com/example/vpmanager/views/mainActivity.java
  app/src/main/java/com/example/vpmanager/views/registerFragment.java
Labels: login, improvement

#206 Bug fix personal account components
  app/src/main/java/com/example/vpmanager/views/homeFragment.java
Labels: bug, pa

#207 Improvement find study carts
  app/src/main/java/com/example/vpmanager/adapter/StudyListAdapter.java
  app/src/main/java/com/example/vpmanager/models/StudyMetaInfoModel.java
  app/src/main/java/com/example/vpmanager/repositories/StudyListRepository.java
  app/src/main/java/com/example/vpmanager/views/SelfcreatedStudiesFragment.java
  app/src/main/res/drawable/ic_baseline_location.xml
  app/src/main/res/drawable/ic_baseline_remote.xml
  app/src/main/res/layout/studylist_cart.xml
Labels: design, find, improvement

#208 Redesign edit study
  app/src/main/java/com/example/vpmanager/adapter/EditSwipeableDatesAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/StudyDatesCreatorAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/viewPagerAdapter.java
  app/src/main/java/com/example/vpmanager/helper/EditSwipeToDeleteCallback.java
  app/src/main/java/com/example/vpmanager/interfaces/EditStudyDetailsListener.java
  app/src/main/java/com/example/vpmanager/interfaces/StudyUpdatedListener.java
  app/src/main/java/com/example/vpmanager/models/DateModel.java
  app/src/main/java/com/example/vpmanager/repositories/StudyEditRepository.java
  app/src/main/java/com/example/vpmanager/repositories/StudyRepository.java
  app/src/main/java/com/example/vpmanager/viewmodels/StudyEditViewModel.java
  app/src/main/java/com/example/vpmanager/views/editStudyFragment.java
  app/src/main/java/com/example/vpmanager/views/studyCreatorDetails/studyCreatorFragment.java
  app/src/main/java/com/example/vpmanager/views/studyDetails/StudyDatesFragment.java
  app/src/main/java/com/example/vpmanager/views/studyDetails/StudyDetailsFragment.java
  app/src/main/java/com/example/vpmanager/views/studyDetails/StudyFragment.java
  app/src/main/java/com/example/vpmanager/views/studyEditDetails/StudyEditDatesFragment.java
  app/src/main/java/com/example/vpmanager/views/studyEditDetails/StudyEditDetailsFragment.java
  app/src/main/java/com/example/vpmanager/views/studyEditDetails/StudyEditFragment.java
  app/src/main/res/layout/fragment_edit_study.xml
  app/src/main/res/layout/fragment_edit_study_dates.xml
  app/src/main/res/layout/fragment_edit_study_details.xml
  app/src/main/res/layout/fragment_study.xml
  app/src/main/res/navigation/nav_graph_main.xml
Labels: design, improvement, architecture

#210 Release v0.1.3
  app/build.gradle
  app/src/main/java/com/example/vpmanager/adapter/EditSwipeableDatesAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/StudyDatesCreatorAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/StudyListAdapter.java
  app/src/main/java/com/example/vpmanager/adapter/viewPagerAdapter.java
  app/src/main/java/com/example/vpmanager/helper/EditSwipeToDeleteCallback.java
  app/src/main/java/com/example/vpmanager/interfaces/EditStudyDetailsListener.java
  app/src/main/java/com/example/vpmanager/interfaces/StudyUpdatedListener.java
  app/src/main/java/com/example/vpmanager/models/DateModel.java
  app/src/main/java/com/example/vpmanager/models/StudyMetaInfoModel.java
  app/src/main/java/com/example/vpmanager/repositories/StudyEditRepository.java
  app/src/main/java/com/example/vpmanager/repositories/StudyListRepository.java
  app/src/main/java/com/example/vpmanager/repositories/StudyRepository.java
  app/src/main/java/com/example/vpmanager/viewmodels/StudyEditViewModel.java
  app/src/main/java/com/example/vpmanager/views/FindStudyFragment.java
  app/src/main/java/com/example/vpmanager/views/SelfcreatedStudiesFragment.java
  app/src/main/java/com/example/vpmanager/views/createStudy/CreateStudyFragment.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyActivity.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepOne.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_StepTwo.java
  app/src/main/java/com/example/vpmanager/views/createStudy/createStudyFragment_finalStep.java
  app/src/main/java/com/example/vpmanager/views/editStudyFragment.java
  app/src/main/java/com/example/vpmanager/views/homeFragment.java
  app/src/main/java/com/example/vpmanager/views/loginFragment.java
  app/src/main/java/com/example/vpmanager/views/mainActivity.java
  app/src/main/java/com/example/vpmanager/views/registerFragment.java
  app/src/main/java/com/example/vpmanager/views/studyCreatorDetails/studyCreatorFragment.java
  app/src/main/java/com/example/vpmanager/views/studyDetails/StudyDatesFragment.java
  app/src/main/java/com/example/vpmanager/views/studyDetails/StudyDetailsFragment.java
  app/src/main/java/com/example/vpmanager/views/studyDetails/StudyFragment.java
  app/src/main/java/com/example/vpmanager/views/studyEditDetails/StudyEditDatesFragment.java
  app/src/main/java/com/example/vpmanager/views/studyEditDetails/StudyEditDetailsFragment.java
  app/src/main/java/com/example/vpmanager/views/studyEditDetails/StudyEditFragment.java
  app/src/main/res/drawable/border.xml
  app/src/main/res/drawable/ic_baseline_location.xml
  app/src/main/res/drawable/ic_baseline_remote.xml
  app/src/main/res/layout/activity_create_study.xml
  app/src/main/res/layout/fragment_create_study_base.xml
  app/src/main/res/layout/fragment_create_study_final_step.xml
  app/src/main/res/layout/fragment_create_study_final_step_three.xml
  app/src/main/res/layout/fragment_create_study_final_step_two.xml
  app/src/main/res/layout/fragment_create_study_step_five.xml
  app/src/main/res/layout/fragment_create_study_step_four_presence.xml
  app/src/main/res/layout/fragment_create_study_step_four_remote.xml
  app/src/main/res/layout/fragment_create_study_step_one.xml
  app/src/main/res/layout/fragment_create_study_step_three.xml
  app/src/main/res/layout/fragment_create_study_step_two.xml
  app/src/main/res/layout/fragment_edit_study.xml
  app/src/main/res/layout/fragment_edit_study_dates.xml
  app/src/main/res/layout/fragment_edit_study_details.xml
  app/src/main/res/layout/fragment_study.xml
  app/src/main/res/layout/material_dropdown_item.xml
  app/src/main/res/layout/studylist_cart.xml
  app/src/main/res/navigation/nav_graph_create.xml
  app/src/main/res/navigation/nav_graph_main.xml
  app/src/main/res/values/strings.xml
Labels: design, improvement, architecture

#212 Bug hotfix appointments
  app/src/main/java/com/example/vpmanager/views/homeFragment.java
Labels: bug

#214 Feature register tooltip
  app/src/main/java/com/example/vpmanager/views/registerFragment.java
  app/src/main/res/drawable/bg_window.xml
  app/src/main/res/drawable/ic_baseline_info_24.xml
  app/src/main/res/drawable/ic_clear.xml
  app/src/main/res/drawable/ic_corner.xml
  app/src/main/res/layout/fragment_register.xml
  app/src/main/res/layout/info_dialog.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: login
